---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-oidc
  annotations:
    cis.f5.com/ipamLabel: prod
spec:
  selector:
    app: nginx-plus-oidc
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
