---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: keycloak-oidc
  namespace: default
spec:
  oidc:
    clientID: nginx-oidc
    clientSecret: keycloak-client-secret
    authEndpoint: http://10.1.10.170:8080/realms/OltraKeyCloak/protocol/openid-connect/auth
    tokenEndpoint: http://10.1.10.170:8080/realms/OltraKeyCloak/protocol/openid-connect/token
    jwksURI: http://10.1.10.170:8080/realms/OltraKeyCloak/protocol/openid-connect/certs
