---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: ssl-pass-1
  namespace: tls-passthrough
spec:
  listener:
    name: tls-passthrough
    protocol: TLS_PASSTHROUGH
  host: tls-1.f5k8s.net
  upstreams:
  - name: ssl-app
    service: secure-app-1
    port: 8443
  action:
    pass: ssl-app
---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: ssl-pass-2
  namespace: tls-passthrough
spec:
  listener:
    name: tls-passthrough
    protocol: TLS_PASSTHROUGH
  host: tls-2.f5demo.cloud
  upstreams:
  - name: ssl-app-2
    service: secure-app-2
    port: 8443
  action:
    pass: ssl-app-2
---

