apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: redirect-tls-coffee
  labels:
    f5cr: "true"
spec:
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
  hosts:
  - coffee.f5demo.local