apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: exdns
  namespace: cluster1
  labels:
    f5cr: "true"
spec:
  domainName: gslb.f5demo.local
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/gtm-primary
    monitor:
      type: tcp
      interval: 3
      timeout: 10
---

apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: exdns
  namespace: cluster2
  labels:
    f5cr: "true"
spec:
  domainName: gslb.f5demo.local
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/gtm-primary
    monitor:
      type: tcp
      interval: 3
      timeout: 10