apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingresslink
spec:
  ingressClassName: nginx-plus
  rules:
  - host: ingresslink.f5demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1-svc
            port:
              number: 80
      - path: /app2
        pathType: Prefix
        backend:
          service:
            name: app2-svc
            port:
              number: 80
