apiVersion: v1
kind: Service
metadata:
  annotations:
    cis.f5.com/health: '{"interval": 3, "timeout": 10}'
    cis.f5.com/ipamLabel: prod
  labels:
    app: svc-health-1
  name: svc-health-1
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: echo
  type: LoadBalancer