apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: single-pool-vs
  labels:
    f5cr: "true"
spec:
  host: single-pool.f5k8s.net
  virtualServerName: "single-pool-vs"
  virtualServerAddress: "10.1.10.55"
  pools:
  - path: /
    service: echo-svc
    servicePort: 80