apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: nginx-plus
  namespace: nginx
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.10"
  virtualServerPort: 80
  virtualServerName: "nginx-plus"
  mode: standard
  snat: auto   
  pool:
    service: nginx-plus
    servicePort: 80
    monitor:
      type: tcp
      interval: 3
      timeout: 10

---
apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: nginx-plus-ssl
  namespace: nginx
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.10"
  virtualServerPort: 443
  virtualServerName: "nginx-plus-ssl"
  mode: standard
  snat: auto   
  pool:
    service: nginx-plus
    servicePort: 443
    monitor:
      type: tcp
      interval: 3
      timeout: 10
---
apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: nginx-plus-dashboard
  namespace: nginx
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.10"
  virtualServerPort: 8080
  virtualServerName: "nginx-plus-dashboard"
  mode: standard
  snat: auto   
  pool:
    service: nginx-plus
    servicePort: 8080
    monitor:
      type: tcp
      interval: 3
      timeout: 10

