apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-plus
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-plus
  template:
    metadata:
      labels:
        app: nginx-plus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/scheme: http
    spec:
      serviceAccountName: nginx-ingress
      imagePullSecrets:
      - name: regcred
      containers:
      - image: private-registry.nginx.com/nginx-ic-nap-dos/nginx-plus-ingress:3.3.2
        imagePullPolicy: IfNotPresent
        name: nginx-plus
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: readiness-port
          containerPort: 8081
        - name: prometheus
          containerPort: 9113
        - name: dashboard
          containerPort: 8080
        - name: service-insight
          containerPort: 9114          
        readinessProbe:
          httpGet:
            path: /nginx-ready
            port: readiness-port
          periodSeconds: 1
#        resources:
#          requests:
#            cpu: "100m"
#            memory: "128Mi"
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 101 #nginx
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-plus
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
          - -wildcard-tls-secret=$(POD_NAMESPACE)/default-server-secret
         #- -enable-tls-passthrough
         #- -enable-snippets
         #- -enable-oidc          
          - -ingress-class=nginx-plus
          - -enable-app-protect
          - -enable-app-protect-dos
         #- -v=3 # Enables extensive logging. Useful for troubleshooting.
          - -report-ingress-status
          - -nginx-status-allow-cidrs=10.0.0.0/8
          - -nginx-status
         # - -disable-ipv6
          - -enable-service-insight 
          - -external-service=nginx-plus
          - -enable-prometheus-metrics
          - -enable-latency-metrics # this is required to get upstream/server location and latency metrics.
          - -global-configuration=$(POD_NAMESPACE)/nginx-configuration
