apiVersion: v1
kind: Service
metadata:
  name: nginx-plus
  namespace: nginx
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    nodePort: 30443
    protocol: TCP
    name: https
  - port: 8080
    targetPort: 8080
    nodePort: 30880
    protocol: TCP
    name: dashboard
  selector:
    app: nginx-plus
