apiVersion: v1
kind: Service
metadata:
  name: echo-svc
#  annotations:
#    cis.f5.com/ipamLabel: dev
#    cis.f5.com/health: '{"interval": 10, "timeout": 31}'
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: echo
#  type: NodePort    