kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx
data:
  allow-snippet-annotations: 'true'
  worker-connections: "10000"
  worker-rlimit-nofile: "10240"
  keepalive: "100"
  keepalive-requests: "100000000"