apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: tcp-ipam-ts
spec:
  ipamLabel: "dev"
  virtualServerPort: 80
  virtualServerName: tcp-ipam-ts
  mode: standard
  snat: auto
  pool:
    service: myapp-svc
    servicePort: 8080
    monitor:
      type: tcp
      interval: 3
      timeout: 10
