apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: basic
spec:
  host: basic-vs.f5k8s.net
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
  - name: coffee
    service: coffee-svc
    port: 80
  - name: echo
    service: echo-svc
    port: 80    
  routes:
  - path: /tea
    action:
      pass: tea
  - path: /coffee
    action:
      pass: coffee
  - path: /
    action:
      pass: echo      