---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-0
  template:
    metadata:
      labels:
        app: myapp-0
    spec:
      containers:
      - name: myapp-0
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-0
  labels:
    app: app-svc-0
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp-0


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-1
  template:
    metadata:
      labels:
        app: myapp-1
    spec:
      containers:
      - name: myapp-1
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-1
  labels:
    app: app-svc-1
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: myapp-1


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-2
  template:
    metadata:
      labels:
        app: myapp-2
    spec:
      containers:
      - name: myapp-2
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-2
  labels:
    app: app-svc-2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp-2


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-3
  template:
    metadata:
      labels:
        app: myapp-3
    spec:
      containers:
      - name: myapp-3
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-3
  labels:
    app: app-svc-3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp-3


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-4
  template:
    metadata:
      labels:
        app: myapp-4
    spec:
      containers:
      - name: myapp-4
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-4
  labels:
    app: app-svc-4
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp-4


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-5
  template:
    metadata:
      labels:
        app: myapp-5
    spec:
      containers:
      - name: myapp-5
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-5
  labels:
    app: app-svc-5
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp-5


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-6
  template:
    metadata:
      labels:
        app: myapp-6
    spec:
      containers:
      - name: myapp-6
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-6
  labels:
    app: app-svc-6
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp-6


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-7
  template:
    metadata:
      labels:
        app: myapp-7
    spec:
      containers:
      - name: myapp-7
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-7
  labels:
    app: app-svc-7
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp-7


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-8
  template:
    metadata:
      labels:
        app: myapp-8
    spec:
      containers:
      - name: myapp-8
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-8
  labels:
    app: app-svc-8
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp-8


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-9
  template:
    metadata:
      labels:
        app: myapp-9
    spec:
      containers:
      - name: myapp-9
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-9
  labels:
    app: app-svc-9
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp-9


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-10
  template:
    metadata:
      labels:
        app: myapp-10
    spec:
      containers:
      - name: myapp-10
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-10
  labels:
    app: app-svc-10
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp-10
