apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: tea
  namespace: app-protect
spec:
  policy:
    applicationLanguage: utf-8
    enforcementMode: blocking
    name: tea
    template:
      name: POLICY_TEMPLATE_NGINX_BASE