apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: coffee
  namespace: app-protect
spec:
  policy:
    applicationLanguage: utf-8
    enforcementMode: blocking
    name: coffee
    template:
      name: POLICY_TEMPLATE_NGINX_BASE