apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: tcp-ts
spec:
  virtualServerAddress: "10.1.10.111"
  virtualServerPort: 80
  virtualServerName: tcp-ts
  mode: standard
  snat: auto
  pool:
    service: myapp-svc
    servicePort: 8080
    monitor:
      type: tcp
      interval: 3
      timeout: 10
