apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: svc1-udp-transport-server
  namespace: default
spec:
  virtualServerAddress: "10.1.10.112"
  virtualServerPort: 8444
  virtualServerName: svc1-udp-ts
  type: udp
  mode: standard
  snat: auto
  pool:
    service: (TODO)
    servicePort: 8182