apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: reencrypt-tls
  labels:
    f5cr: "true"
  namespace: nginx-ingress
spec:
  tls:
    termination: edge
    clientSSL: default-server-secret
    reference: secret            # --> reference profiles created in BIG-IP by User
  hosts:
  - coffee.example.com

#        serverSSL: /Common/serverssl
