apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  name: coffee-virtual-server2
  labels:
    f5cr: "true"
  namespace: nginx-ingress
spec:
  virtualServerAddress: "192.168.3.39"
  host: www.example.com
  pools:
    - path: /
      service: nginx-plus
      servicePort: 80
      monitor:
        type: http
        send: “GET /rn”
        recv: ""
        interval: 10
        timeout: 10    