apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: rate-limit
spec:
  host: rate.f5k8s.net
  policies:
  - name: rate-limit-policy
  upstreams:
  - name: webapp
    service: webapp-svc
    port: 80
  routes:
  - path: /
    action:
      pass: webapp
