apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  name: wildcard-vs
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: 10.1.10.93
  virtualServerName: "wildcard-vs"
  host: '*.f5demo.local'
  snat: auto
  pools:
    - path: /
      service: echo-svc
      servicePort: 80
