apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: edge-tls
  labels:
    f5cr: "true"
spec:
  hosts:
    - edge.f5demo.local
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
