apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: edge-tls-vs
spec:
  host: edge.f5demo.local
  tlsProfileName: edge-tls
  virtualServerAddress: 10.1.10.121
  virtualServerName: "edge-tls-vs"
  pools:
  - path: /
    service: echo-svc
    servicePort: 80