apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: passthrough-tls-vs
spec:
  host: passthrough.f5demo.local
  tlsProfileName: passthrough-tls
  virtualServerAddress: 10.1.10.123
  virtualServerName: "passthrough-tls-vs"
  pools:
  - path: /
    service: secure-app
    servicePort: 8443

