apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-k8s
spec:
  ingressClassName: nginx
  rules:
  - host: community.f5demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo-svc
            port:
              number: 80