apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: nginx-k8s
  namespace: ingress-nginx
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "192.168.6.200"
  virtualServerPort: 80
  virtualServerName: "nginx-k8s"
  mode: standard
  snat: auto   
  pool:
    service: ingress-nginx-controller 
    servicePort: 80
    monitor:
      type: tcp
      interval: 10
      timeout: 10