apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: webapp 
spec:
  host: webapp.f5demo.local
  policies:
  - name: webapp-policy
  upstreams:
  - name: webapp 
    service: app1-svc
    port: 80
  routes:
  - path: /
    action:
      pass: webapp