apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: grafana-storage
  local:
    path: /home/ubuntu/grafana-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "node02"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-claim
  namespace: monitoring
spec:
  storageClassName: grafana-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi