apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx-plus
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: nginx.org/ingress-controller
  parameters:
    kind: IngressParameters
    name: nginx-plus