apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: xff-policy-vs
spec:
  virtualServerAddress: 10.1.10.97
  virtualServerName: "xff-policy-vs"
  host: policy.f5demo.local
  policyName: xff-policy
  snat: auto
  pools:
  - path: /
    service: echo-svc
    servicePort: 80