apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: waf-policy-vs
spec:
  virtualServerAddress: 10.1.10.98
  virtualServerName: "waf-policy-vs"
  host: waf.f5demo.local
  policyName: waf-policy
  snat: auto
  pools:
  - path: /
    service: echo-svc
    servicePort: 80