apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: ipam1-hostgroup-vs
  labels:
    f5cr: "true"
spec:
  host: ipam1.f5demo.local
  ipamLabel: "dev"
  virtualServerName: "hostgroup-ipam-vs"  
  hostGroup: "apps"
  pools:
    - path: /
      service: app1-svc
      servicePort: 8080
---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: ipam2-hostgroup-vs
  labels:
    f5cr: "true"
spec:
  host: ipam2.f5demo.local
  ipamLabel: "dev"
  virtualServerName: "hostgroup-ipam-vs"  
  hostGroup: "apps"
  pools:
    - path: /
      service: app2-svc
      servicePort: 8080