apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: ipam-vs
  labels:
    f5cr: "true"
spec:
  host: ipam.f5demo.local
  ipamLabel: "dev"
  virtualServerName: "ipam-vs"
  pools:
  - path: /
    service: echo-svc
    servicePort: 80