apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: nginx-plus
  namespace: nginx
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "192.168.3.48"
  virtualServerPort: 80
  virtualServerName: "nginx-plus"
  persistenceProfile: none
  mode: standard
  snat: auto   
  pool:
    service: nginx-plus
    servicePort: 80
    monitor:
      type: tcp
      interval: 10
      timeout: 10

---
apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: nginx-plus-ssl
  namespace: nginx
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "192.168.3.48"
  virtualServerPort: 443
  virtualServerName: "nginx-plus-ssl"
  persistenceProfile: none
  mode: standard
  snat: auto   
  pool:
    service: nginx-plus
    servicePort: 443
    monitor:
      type: tcp
      interval: 10
      timeout: 10

