apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: hg1-hostgroup-vs
  labels:
    f5cr: "true"
spec:
  host: hg1.f5k8s.net
  virtualServerName: "hostgroup-vs"
  virtualServerAddress: "10.1.10.59"
  hostGroup: "apps"
  pools:
    - path: /
      service: app1-svc
      servicePort: 8080
---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: hg2-hostgroup-vs
  labels:
    f5cr: "true"
spec:
  host: hg2.f5k8s.net
  virtualServerName: "hostgroup-vs"
  virtualServerAddress: "10.1.10.59"
  hostGroup: "apps"
  pools:
    - path: /
      service: app2-svc
      servicePort: 8080