apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nginxdemos/nginx-hello:0.1-plain-text
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: nginxdemos/nginx-hello:0.1-plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app1-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: app1
---
apiVersion: v1
kind: Service
metadata:
  name: app2-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: app2
---
apiVersion: v1
kind: Secret
metadata:
  name: apps-tls-secret
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU1RENDQTh5Z0F3SUJBZ0lTQkZibUVsQjA5SWc4eFZCRDErOGVSSFNYTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURNeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rd3dDZ1lEVlFRRApFd05TTVRFd0hoY05NalV3TVRBNE1EVTBOVFUwV2hjTk1qVXdOREE0TURVME5UVXpXakFXTVJRd0VnWURWUVFECkRBc3FMbVkxYXpoekxtNWxkRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNY1EKSEthYXhuSmFLVWdRdURCelY5TmRqbnlpV3V2NThrKy9yZ3ZGWU5WQUdQekRieUE3TWNycU9aV3dXNG9LMENPaApKSndIMm1rakUzN2hqckd2Z0xHdXlyWXFIRFdDNEgrTkhiVGg4SWZVbUhXMmoyR2FSWmx2WEJBRW5KZ1JFdjdECmRmbmUrbGZZb3JDclF6cUMzbGdmYXc2cHpUcElhbzg5WnlYSEVVOTduYytvTkt5VGxSYjBjSUF1eVNGZytXY0IKbm9Rc0ZSOWtOVlNlNUg5Y3N4WkdVTERyZFVXdW5QTSszREtvSDZCM2RCb1VPYmkzcHFwazRQcHlJVkFhMk9SUApZV3RIaE1zTlFZU3pQZ2dhbE5kR2hDbytIdFUwenNkWlhBMmtzeE1GTzhuSjhaSUk2UzIvTU5memw2bHB4aXN4CjhuTG5kd0ltUlVTWENDVEZPV1VDQXdFQUFhT0NBZzB3Z2dJSk1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlYKSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RQpGZ1FVS1NhbnEzK0xtZStRaktTUmxTaWpVOUd5NDQ0d0h3WURWUjBqQkJnd0ZvQVV4YzlHcE9yMHc4QjZiSlhFCkxiQmVraThtNDdrd1Z3WUlLd1lCQlFVSEFRRUVTekJKTUNJR0NDc0dBUVVGQnpBQmhoWm9kSFJ3T2k4dmNqRXgKTG04dWJHVnVZM0l1YjNKbk1DTUdDQ3NHQVFVRkJ6QUNoaGRvZEhSd09pOHZjakV4TG1rdWJHVnVZM0l1YjNKbgpMekFXQmdOVkhSRUVEekFOZ2dzcUxtWTFhemh6TG01bGREQVRCZ05WSFNBRUREQUtNQWdHQm1lQkRBRUNBVENDCkFRSUdDaXNHQVFRQjFua0NCQUlFZ2ZNRWdmQUE3Z0IxQUtMakN1UkY3NzJ0bTM0NDdVZG5kMVBYZ2x1RWxOY3IKWGhzc3hMbFFwRWZuQUFBQmxFU29RVjRBQUFRREFFWXdSQUlnZU1SRUVEcUNpeWYxRDdCYjdncTh0S2lmdWlGTQorOFRuUzk5dHdpV0VJQTRDSUJZM01XaEorZUpvcUhHendmdTZQYmgvQUJJdGJ0MSt6YW1RT0NCZXU1YlpBSFVBClRuV2pKMXlhRU1NNFcyelUzejlTNngzdzRJNGJqV25Bc2Zwa3NXS2FPZDhBQUFHVVJLaEJYd0FBQkFNQVJqQkUKQWlBSm9nZE9TTWNkclAwM0JqK1VXS2ZYSFhuWlhzTGpvcmQ0RXI1Z014YWhVd0lnZXVieXcySTh4WVdsS3pEYwo1aExOOWdHK0RFR0dkWUd0NEJuSHZVdVhJdjB3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUtTcGMwd3hrM1M4CmtsK2NVeGpTM2E5clVHcG9TeWhXZmJCaEVEeFFqdzJiVHEyUW1FNHRqUlNGQVA3dXRSaGFQWWNlMFlHeDUrdnEKbzlaS09qTnBBRnVPRmJNRGd2bkJtcDhXNnJTbTU5dnFOWUlwc3pGaVhoU3BQUVFXaTNEVFlLTmR3bzNFNE1UegpEMDQySldVcnhZNFZhMkFVd1VSdjVvaGsvODU3czB2OXB0ZVFsMU9GYkxhdlBUUVcxendrNFZ5Zk5VT0Fhc0hvCkVER2RxT0FWZmFjdi83MkVZYWxLZWljVmlmNnlCbGlia1hiWUFrRWxNeDk3WEM1b3BOcURxMVJobzlPYUYxVnEKTDVKbUZJYjUvMTZONFU4QitJWTRNenk2UWgrYmpMQ3RONmlQajlqY0lJTERwc0tZeVFCbWNuUVluamc3TUZOUAp5anJaQVhQNUhVcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRkJqQ0NBdTZnQXdJQkFnSVJBSXA5UGhQV0x6RHZJNGE5S1Fkck5QZ3dEUVlKS29aSWh2Y05BUUVMQlFBdwpUekVMTUFrR0ExVUVCaE1DVlZNeEtUQW5CZ05WQkFvVElFbHVkR1Z5Ym1WMElGTmxZM1Z5YVhSNUlGSmxjMlZoCmNtTm9JRWR5YjNWd01SVXdFd1lEVlFRREV3eEpVMUpISUZKdmIzUWdXREV3SGhjTk1qUXdNekV6TURBd01EQXcKV2hjTk1qY3dNekV5TWpNMU9UVTVXakF6TVFzd0NRWURWUVFHRXdKVlV6RVdNQlFHQTFVRUNoTU5UR1YwSjNNZwpSVzVqY25sd2RERU1NQW9HQTFVRUF4TURVakV4TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCCkNnS0NBUUVBdW9lOFhCc0FPY3ZLQ3MzVVp4RDVBVHlsVHFWaHl5YktVdnNWQWJlNUtQVW9IdTBuc3lRWU9XY0oKREFqczREcXdPM2NPdmZQbE9WUkJERTZ1UWRhWmRONVIyKzk3LzFpOXFMY1Q5dDR4MWZKeXlYSnFDNE4wbFp4RwpBR1FVbWZPeDJTTFp6YWlTcWh3bWVqLys3MWdGZXdpVmdkdHhENDc3NHpFSnV3bStVRTFmajVGMlBWcWRub1B5CjZjUm1zK0VHWmtOSUdJQmxvRGNZbXB1RU1wZXhzcjNFK0JVQW5TZUkrK0pqRjVac215ZG5TOFRiS0Y1cHdubncKU1Z6Z0pGRGh4THloQmF4N1FHMEF0TUpCUDZkWXVDL0ZYSnVsdXdtZThmN3JzSVU1L2FnSzcwWEVlT3RsS3NMUApYenplNDF4TkcvY0xKeXVxQzBKM1UwOTVhaDJIMlFJREFRQUJvNEg0TUlIMU1BNEdBMVVkRHdFQi93UUVBd0lCCmhqQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBZ1lJS3dZQkJRVUhBd0V3RWdZRFZSMFRBUUgvQkFnd0JnRUIKL3dJQkFEQWRCZ05WSFE0RUZnUVV4YzlHcE9yMHc4QjZiSlhFTGJCZWtpOG00N2t3SHdZRFZSMGpCQmd3Rm9BVQplYlJaNW51MjVlUUJjNEFJaU1nYVdQYnBtMjR3TWdZSUt3WUJCUVVIQVFFRUpqQWtNQ0lHQ0NzR0FRVUZCekFDCmhoWm9kSFJ3T2k4dmVERXVhUzVzWlc1amNpNXZjbWN2TUJNR0ExVWRJQVFNTUFvd0NBWUdaNEVNQVFJQk1DY0cKQTFVZEh3UWdNQjR3SEtBYW9CaUdGbWgwZEhBNkx5OTRNUzVqTG14bGJtTnlMbTl5Wnk4d0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnSUJBRTdpaVYwS0F4eVFPTkQxSC9seFhQakRqN0kzaUhwdnNDVWY3YjYzMklZR2p1a0poTTF5CnY0SHovTXJQVTBqdHZmWnBRdFNsRVQ0MXlCT3lraDBGWCtvdTFOajRTY090OVptV25POG0yT0cwSkF0SUlFMzgKMDFTMHFjWWh5T0UyRy85M1pDa1h1ZkJMNzEzcXpYblF2NUMvdmlPeWtOcEtxVWd4ZEtsRUMrSGk5aTJEY2FSMQplOUtVd1FVWlJoeTVqL1BFZEVnbEtnM2w5ZHRENHR1VG03a1p0Qjh2MzJvT2p6SFRZdys3S2R6ZFppdy9zQnRuClVmaEJQT1JOdWF5NHBKeG1ZL1dyaFNNZHpGTzJxM0d1M01VQmNkbzI3Z29ZS2pMOUNURjhqL1p6NTV5Y3RVb1YKYW5lQ1dzL2FqVVgrSHlwa0JUQStjOExHRExuV08yTktxMFlEL3BuQVJrQW5ZR1BmVURvSFI5Z1ZTcC9xUngrWgpXZ2hpRExac013aE4xemp0U0MwdUJXaXVnRjN2VE56WUlFRmZhUEc3V3MzakRyQU1NWWViUTk1SlErSElCRC9SClBCdUhSVEJwcUtseURua1NIREhZUGlOWDNhZFBvUEFjZ2RGM0gyL1cwcm1vc3dNV2dUbExuMVd1MG1ya3M3L3EKcGRXZlM2UEoxanR5ODByMlZLc00vRGozWUlEZmJqWEtkYUZVNUMrOGJoZkpHcVUzdGFLYXV1ejB3SFZHVDNlbwo2RmxXa1dZdGJ0NHBnZGFtbHdWZVpFVytMTTdxWkVKRXNNTlByZkMwM0FQS21ac0pncFdDRFdPS1p2a1pjdmpWCnVZa1E0b21ZQ1RYNW9oeStrbk1qZE9tZEg5YzdTcHFFV0JEQzg2ZmlOZXgrTzBYT01FWlNhOERBCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRREhFQnltbXNaeVdpbEkKRUxnd2MxZlRYWTU4b2xycitmSlB2NjRMeFdEVlFCajh3MjhnT3pISzZqbVZzRnVLQ3RBam9TU2NCOXBwSXhOKwo0WTZ4cjRDeHJzcTJLaHcxZ3VCL2pSMjA0ZkNIMUpoMXRvOWhta1daYjF3UUJKeVlFUkwrdzNYNTN2cFgyS0t3CnEwTTZndDVZSDJzT3FjMDZTR3FQUFdjbHh4RlBlNTNQcURTc2s1VVc5SENBTHNraFlQbG5BWjZFTEJVZlpEVlUKbnVSL1hMTVdSbEN3NjNWRnJwenpQdHd5cUIrZ2QzUWFGRG00dDZhcVpPRDZjaUZRR3Rqa1QyRnJSNFRMRFVHRQpzejRJR3BUWFJvUXFQaDdWTk03SFdWd05wTE1UQlR2SnlmR1NDT2t0dnpEWDg1ZXBhY1lyTWZKeTUzY0NKa1ZFCmx3Z2t4VGxsQWdNQkFBRUNnZ0VBS2ZudURMelZEWDZSTjNMZElFeG1UL29weG9MbStOMVZXVGRDa0pWZjBNQXEKTkx6U2RXRytJM3VtUm5nd3FXaVQwUHVWVUhqQWVBeXZPd0Y5MlY2NG5OOU92RUNmZjdJNFBIVnB0dit3L0xlYQpLYkprUkZEbmpjNGpnL1l3L2trVmNCY1FETytWNjBuUnJyOENsM2RLd3hybTlLbmVUc1RBQWJJUlN2QlNLR2Y1CnN1RHo0NDNLNnN3SUFxdytCdDRXZW9nNjVIbVN1bTB4R2NuK3NCT2p1dTZVMzZBUW5sbVVjQzJtaUh3ZE5obk8KL210WmtEZUNic2t1RXp2UE9idFB1cHB4MWJ3TG5Ka0tudVRlKzhYcytMRlFZeXBJZEZDUXBvTE04bFdtMGtLdQpyK1MxbkhHVUVrY0VyZWJnZkhBUHp2YW40dnFiRWd3Yjc5VGdyVU5rT1FLQmdRRHYyVU13dmJnVWpTOVppNWpyCldSRWZhbkVGL1ZCbFR3YzQyNU5mQTlpcy9CU3FMZGZRV3lFcXVzeWVyZFYwelcvVDJPVy9adUFEOThhYlZrVzMKckZicm9pQ2dlc0xBK0ZpZlU1NDRhMFdvNGhaN1JyczVqQ2NpRjVFSmx0ckRzQ2VJNGVKL1hlVTFhSHg0VXdBOApFYVQzSFViUFNwNG4rYjd6TVhjMWRDenU3UUtCZ1FEVWQ3OFNER0cwdUI1UXF4OTZvU3c2U0ZEVDNZVUtadWJYCnlUWWVSek93R2pLTEQxZmRSeGlIcHlHa1pTcThyWDEzVFhoN2ZFamFUbnZJVTV2enpCTEduU3pMdnIzY0FpY00KaC9xM0ZmZkdiaDRmL1NHNzR2WWo0M2g1YXYzZnhadjRwZXc1cTJpaW14eWJwcHphRG5QWlN3eVArdUVIeHMrSApZM1FQekhDdFdRS0JnUURUcWp5dGl3QWt3dVFDZGp1aGxweVJ5UEd0ZzN1cnJDNkhjdDkvZm5sOVQ0azlGZS9iCkpGRUUwSTA3aTlWUW11d1JYTnlFS1ZtUXB0MVN3TFFOLzcxRmZYS2xyVENwODREaU9uenE5V0FvUmozbzFPYnQKUms1U3U5RjNVUFlHdERKdmprakFkakNORFlTcSt6Uzl6aVJ6SUJjWllKUnFXdkMwMWZhSjZkaXRrUUtCZ0FteQpXVjhLZjU4TzFCdGNZL2hseUszMFJQUVdaUTcvZVVPWjVFVm5mSDFxQktxQ0RjR0VrQ01JeHFsSkVMVkJ1YnNyCkp2ZUR5Wk5sQjVNeDlha2Z4QythVnNRSnRZS0grcDVBeW5sMm9ETkhMVXJLYzdLdWZndFBRMTFQTzd6dHVOdVYKUHYyMnkvUzMzWXRoQkVHVGJVZ2FlNzFLZHVDeSt4K3pzMFZSVUVjcEFvR0FLZ1JVajc4eU1wbXkxM2VGbUpFeQprMlJvRnhYdHVyaUtyMVlPWW15NHNlZ1grQ2tLaUtIMDRQcTQ0NFRmWjM0YzJvWXRjR2hEa3Zvc0txNHB1SjlrCnVuTUN5UytMOCtmSmQ3RHQ2eDJVVWZlZjlqWFY0MjV3N3YxTUY0WEhocFdZV1dDUWlrM0c0dG8vWDF4a2tPSXIKUkdLV0lkMHZJaUYvQWo1OCt3TFJ2U1E9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
type: kubernetes.io/tls
