apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: readiness
  template:
    metadata:
      labels:
        app: readiness
    spec:
      containers:
      - name: readiness
        image: skenderidis/readiness
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: readiness