apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: echo-test
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "192.168.3.161"
  virtualServerPort: 80
  virtualServerName: "echo-test"
  mode: standard
  snat: auto
  pool:
    service: echo-svc
    servicePort: 80