apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: nginx-oss-ssl
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "192.168.3.60"
  virtualServerPort: 443
  virtualServerName: "nginx-oss-ssl"
  mode: standard
  snat: auto   
  pool:
    service: nginx-oss
    servicePort: 443
    monitor:
      type: tcp
      interval: 10
      timeout: 10