apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-app1
  labels:
    f5cr: "true"
spec:
  domainName: edns.f5demo.local
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/gtm-primary
    monitor:
      type: tcp
      interval: 3
      timeout: 10
