apiVersion: "cis.f5.com/v1"
kind: IngressLink
metadata:
  name: nginx-ingress
  namespace: nginx
spec:
  virtualServerAddress: "10.1.10.5"
#  iRules:
#    - /Common/Proxy_Protocol_iRule
  selector:
    matchLabels:
      app: ingresslink