apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: l7-app2
  namespace: layer7
  labels:
    f5cr: "true"
spec:
  host: "l7-app2.f5demo.local"
  policyName: app2-waf-policy
  ipamLabel: "prod"
  virtualServerName: "l7-www"
  pools:
  - path: /
    service: app2-svc
    servicePort: 8080