apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: nginx-tls
  namespace: nginx
  labels:
    f5cr: "true"
spec:
  hosts:
    - "*.f5demo.local"
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/serverssl
    reference: bigip