apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: l7-www
  namespace: layer7
  labels:
    f5cr: "true"
spec:
  host: "l7-www.f5demo.local"
  policyName: www-waf-policy
  ipamLabel: "prod"
  virtualServerName: "l7-www"
  pools:
  - path: /
    service: echo-svc
    servicePort: 80