---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ipam
  namespace: bigip
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi