apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipam-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /home/ubuntu/ipam
#  Removing nodeAffinity since we are working on Single Node Cluster
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
#          - "node01"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ipam
  namespace: bigip
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi