apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: irule-policy-vs
spec:
  virtualServerAddress: 10.1.10.63
  virtualServerName: "irule-policy-vs"
  host: irule.f5k8s.net
  policyName: irule-policy
  snat: auto
  pools:
  - path: /
    service: echo-svc
    servicePort: 80