apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: redirect-vs
  namespace: default
spec:
  tlsProfileName: redirect-tls
  virtualServerAddress: 10.1.10.60
  virtualServerName: "redirect-tls-vs"
  httpTraffic: redirect
  host: redirect.f5k8s.net
  pools:
    - path: /lattee
      service: app1-svc
      servicePort: 8080
    - path: /mocha
      service: app2-svc
      servicePort: 8080
