apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: nohost-vs
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.90"
  virtualServerName: "nohost-vs"
  pools:
  - path: /
    service: echo-svc
    servicePort: 80