kind: Secret
metadata:
  name: cafe-passwd
apiVersion: v1
type: nginx.org/htpasswd
stringData:
  htpasswd: |
    foo:$2y$10$e4CiBWaLq9JW93jV8r9CW.RE6fbsT3szmIsUhwqYuPfVlggXiBY76
    qux:$apr1$st218vzc$A3H7I83N9vLmczj73Byi3/
  # bar
  # quux
