apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy-monitor
  namespace: nap
spec:
  waf:
    enable: true
    apPolicy: "nap-monitor"
    securityLogs:
    - enable: true
      apLogConf: "logconf"
      logDest: "syslog:server=10.1.20.20:8515"
