apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: rewrite-vs
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.62"
  virtualServerName: "rewrite-vs"
  host: rewrite.f5k8s.net
  pools:
    - path: /lab
      service: app1-svc
      servicePort: 8080
      rewrite: /laboratory
    - path: /lib
      service: app2-svc
      servicePort: 8080
      rewrite: /library
