apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  name: coffee-virtual-server
  labels:
    f5cr: "true"
  namespace: nginx-ingress
spec:
  host: coffee.example.com
  tlsProfileName: reencrypt-tls  # --> This will attach reencrypt-tls TLSProfile
  virtualServerAddress: "172.16.3.4"
  pools:
    - path: /
      service: nginx-plus
      servicePort: 80