apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: zipkin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: zipkin
    spec:
      containers:
      - image: openzipkin/zipkin:2.21
        imagePullPolicy: IfNotPresent
        name: zipkin
        ports:
        - containerPort: 9411
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-collector
  namespace: monitoring
spec:
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
    nodePort: 30102
  selector:
    app.kubernetes.io/name: zipkin
  sessionAffinity: None
  type: NodePort

