apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: f5-ipam
  name: f5-ipam
  namespace: bigip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5-ipam
  template:
    metadata:
      labels:
        app: f5-ipam
    spec:
      containers:
      - args:
        - --orchestration=kubernetes
        - --ip-range='{"nginx-plus":"10.1.10.10-10.1.10.10", "dev":"10.1.10.150-10.1.10.169","prod":"10.1.10.170-10.1.10.189","tenant1":"10.1.10.190-10.1.10.192","tenant2":"10.1.10.193-10.1.10.195"}'
        - --log-level=DEBUG
        command:
        - /app/bin/f5-ipam-controller
        image: f5networks/f5-ipam-controller:0.1.9
        imagePullPolicy: IfNotPresent
        name: f5-ipam-controller
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /app/ipamdb
          name: samplevol
      securityContext:
        fsGroup: 1200
        runAsGroup: 1200
        runAsUser: 1200
      serviceAccount: bigip-ctlr
      serviceAccountName: bigip-ctlr
      volumes:
      - name: samplevol
        persistentVolumeClaim:
          claimName: pvc-ipam
          