apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: nap-cafe
  namespace: nap
spec:
  host: nap-cafe.f5demo.cloud
  policies:
  - name: cocoa-policy
  upstreams:
  - name: cocoa
    service: cocoa-svc
    port: 80
  - name: coffee
    service: coffee-svc
    port: 80
  - name: tea
    service: tea-svc
    port: 80    
  routes:
  - path: /
    action:
      pass: cocoa
  - path: /tea
    policies:
    - name: tea-policy
    action:
      pass: tea
  - path: /coffee
    policies:
    - name: coffee-policy
    action:
      pass: coffee
