apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: approot-vs
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.61"
  virtualServerName: "approot-vs"
  rewriteAppRoot: /home
  host: approot.f5k8s.net
  pools:
    - path: /
      service: app1-svc
      servicePort: 8080
